lexik_jwt_authentication:
  secret_key: "%env(resolve:JWT_SECRET_KEY)%"
  public_key: "%env(resolve:JWT_PUBLIC_KEY)%"
  pass_phrase: "%env(JWT_PASSPHRASE)%"
  token_ttl: 9000
  user_identity_field: email

  token_extractors:
    authorization_header:
      enabled: false
      prefix: Bearer
      name: Authorization
    cookie:
      enabled: true
      name: BEARER
