security:
  encoders:
    App\Entity\JobSeeker:
      algorithm: argon2i

    App\Entity\Employeur:
      algorithm: argon2i

  providers:
    all_users:
      chain:
        providers: ["jobseeker", "employeur"]
    jobseeker:
      entity: { class: App\Entity\JobSeeker, property: email }
    employeur:
      entity: { class: App\Entity\Employeur, property: email }
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    jobseeker_login:
      pattern: ^/api/login/jobseeker
      stateless: true
      anonymous: true
      provider: jobseeker
      json_login:
        check_path: /api/login/jobseeker
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    employeur_login:
      pattern: ^/api/login/employeur
      stateless: true
      anonymous: true
      provider: employeur
      json_login:
        check_path: /api/login/employeur
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    refresh:
      pattern: ^/api/token/refresh
      stateless: true
      anonymous: true

    # register:
    #   pattern: ^/api/register
    #   stateless: true
    #   anonymous: true

    api:
      pattern: ^/api
      stateless: true
      anonymous: true
      provider: all_users
      guard:
        authenticators:
          - lexik_jwt_authentication.jwt_token_authenticator

    main:
      anonymous: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/api/login/jobseeker, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/login/employeur, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/token/refresh, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
