#index:
#    path: /
#    controller: App\Controller\DefaultController::index
jobseeker_login:
    path: /api/login/jobseeker
employeur_login:
    path: /api/login/employeur

gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh